### PR TITLE
Add API to get matches by EventId

### PR DESCRIPTION
**Pull request by henriqueln7**
This PR adds a parameter `eventId` on `getMatches` method to filter matches for a specific event.

### CODE REVIEW

**Comment by henriqueln7** [comment]
Hey, @dajk. Just one question: when will you publish those changes? I can create a specific version to make your job easier if you want :)

**Comment by dajk** [comment]
Hi @henriqueln7 , I published this with the version `3.0.3`, however seems to be broken and I will have to revert and release the new version.

I also had doubts about this function, is this really necessary considering we never had a way to expose an `eventId`?

**Comment by henriqueln7** [comment]
Hey, @dajk. Good question. What you think if we implement a `getUpcomingEvents()` endpoint or similar?
Let me know if you think it is a good ideia, I can work on it :D

**Comment by dajk** [comment]
> Hey, @dajk. Good question. What you think if we implement a `getUpcomingEvents()` endpoint or similar? Let me know if you think it is a good ideia, I can work on it :D

That would make sense, but also ongoing events would be even more important in my opinion. Unfortunately there is no `eventId` on the match, we only get the event's name and logo.

**Comment by henriqueln7** [comment]
> That would make sense, but also ongoing events would be even more important in my opinion. Unfortunately there is no `eventId` on the match, we only get the event's name and logo.

Sure, I think `ongoing events` is more important. I can work on it. :)

**Pull request merged**
